MatteoTarabella04/BoolBnB

- back-end/app/Http/Controllers/API/RegisteredUserController.php
- back-end/app/Http/Controllers/Auth/RegisteredUserController.php
FIX registration validation rules
> FIX registration validation rules

- front-end/src/router.js
- front-end/src/views/UserRegistrationView.vue
> 3 registration page front

- front-end/src/views/UserLoginView.vue
- front-end/src/views/UserRegistrationView.vue
> fix v-model.trim

- back-end/resources/views/admin/apartments/create.blade.php
- back-end/resources/views/admin/apartments/edit.blade.php
- back-end/resources/views/admin/apartments/index.blade.php
- back-end/resources/views/admin/apartments/show.blade.php
- front-end/src/views/ApartmentViews/AddApartmentView.vue
- front-end/src/views/ApartmentViews/EditApartmentView.vue
- front-end/src/views/ApartmentViews/ShowApartmentView.vue
> 20 crud front

- back-end/resources/views/admin/apartments/create.blade.php
- back-end/resources/views/admin/apartments/edit.blade.php
> fix edit page graphic

- back-end/resources/views/admin/apartments/edit.blade.php
> fix some bugs

- back-end/app/Http/Controllers/Admin/ApartmentController.php
- back-end/resources/js/registration-validation.js
- back-end/resources/views/auth/register.blade.php
- back-end/resources/views/layouts/app.blade.php
Validations for password and date
> Registration js validation

- back-end/app/Http/Controllers/Auth/RegisteredUserController.php
- back-end/package-lock.json
- back-end/package.json
- back-end/resources/js/bootstrap.js
- back-end/resources/js/insertAddress.js
- back-end/resources/js/registration-validation.js
- back-end/resources/scss/app.scss
- back-end/resources/views/admin/apartments/create.blade.php
ADD map and address integration on create apartment page
> New address latitude longitude implementation

- back-end/resources/js/insertAddress.js
- back-end/resources/scss/app.scss
- back-end/resources/scss/partials/colors.scss
> Crud branch

- back-end/package-lock.json
- back-end/package.json
- back-end/resources/scss/app.scss
- back-end/resources/views/admin/apartments/index.blade.php
> add scss specs + fix layout structure index.blade

- back-end/resources/scss/app.scss
- back-end/resources/views/admin/apartments/show.blade.php
> Change layout card backend

- back-end/resources/views/admin/apartments/index.blade.php
add responsive layout index.blade
> add responsive layout index.blade

- back-end/package-lock.json
- back-end/package.json
> add package-json modified with chart.js

- back-end/app/Http/Controllers/Admin/ApartmentController.php
- back-end/app/Http/Requests/UpdateApartmentRequest.php
- back-end/app/Providers/AppServiceProvider.php
- back-end/resources/views/admin/apartments/create.blade.php
- back-end/resources/views/admin/apartments/edit.blade.php
- back-end/resources/views/admin/apartments/index.blade.php
fix images errors
fix visibility
add pagination
> Mattiavolpe2

- front-end/src/views/SingleApartment.vue
- package-lock.json
> add offcanvas style

- back-end/app/Http/Controllers/Auth/RegisteredUserController.php
FIX date_of_birth back-end validation
> FIX date_of_birth back-end validation

- back-end/app/Http/Controllers/API/ApartmentController.php
- back-end/resources/js/insertAddress.js
- back-end/routes/api.php
- front-end/src/views/HomeView.vue
ADD basic filters for beds, rooms and distance
> 58 search front

- front-end/src/views/SingleApartment.vue
Add some elements + add some style
TODO: add header component + fix and add more elements
> ADD some elements to page + add some style

- back-end/app/Http/Controllers/Admin/MessageController.php
- back-end/app/Models/Apartment.php
- back-end/app/Models/Message.php
- back-end/app/Models/User.php
- back-end/resources/views/admin/apartments/message.blade.php
- back-end/routes/web.php
add message receiver working with back and front end
> add message receiver

- front-end/src/styles/partials/_HomeView.scss
- front-end/src/styles/partials/_Utilities.scss
- front-end/src/views/SingleApartment.vue
change layout home and single page
> Dami front6

- back-end/app/Http/Controllers/Admin/MessageController.php
- back-end/resources/views/admin/apartments/message.blade.php
- back-end/resources/views/partials/AppHeader.blade.php
- back-end/routes/web.php
REMOVE links to the same page you already are from the dropdown in the admin page
ADD controller functions to sort the messages by descendant send_date
> Mattia various fixes and implementations

- front-end/src/store.js
- front-end/src/views/HomeView.vue
- front-end/src/views/SearchPage.vue
- front-end/src/views/SingleApartment.vue
fix arrow keys bug and change single page
> Dami front8

- front-end/src/styles/general.scss
- front-end/src/styles/partials/_Colors.scss
- front-end/src/styles/partials/_HomeView.scss
- front-end/src/styles/partials/_Utilities.scss
- front-end/src/styles/partials/_animation.scss
- front-end/src/styles/partials/_modal_customitation.scss
- front-end/src/views/SearchPage.vue
> Dami front10
